export default {
  namespaced: true,
  state: {
    events: [
      {
        id: 1,
        userId: '',
        title: 'Dance_Fest',
        date: '2020/05/13', // ADD ISO FORMAT ---  YYYY-MM-DDTHH:mm:ss.sssZ
        time: '13:00',
        address: {
          street: 'Rua do Dinar',
          neighborhood: 'Vila Carlota',
          city: 'campo grande',
        },
        ticket: '0',
        link: 'https://www.facebook.com/henriquemleonel',
        description: 'Festival de dança da comunidade para a comunidade, venha se divertir',
        categoryId: 1,
        imgUrl: '../assets/statics/avatar01.jpg',
      },
      {
        id: 2,
        userId: '',
        title: 'Festival Forró',
        date: '2020/04/05', // format iso YYYY/MM/DD
        time: '18:00',
        address: { street: 'rua festeja', neighborhood: 'centro', city: 'campo grande' },
        ticket: '0',
        link: 'https://www.facebook.com/henriquemleonel',
        description: 'pula fogueira',
        categoryId: 12,
        imgUrl: '../assets/statics/avatar01.jpg',
      },
      {
        id: 3,
        userId: '',
        title: '"Como não viver em isolamento"',
        date: '2020/05/07',
        time: '18:00',
        address: { street: 'rua festeja', neighborhood: 'centro', city: 'campo grande' },
        ticket: '0',
        link: 'https://www.facebook.com/henriquemleonel',
        description: 'pula fogueira Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica ede impressos,',
        categoryId: 1,
        imgUrl: '../assets/statics/avatar01.jpg',
      },
      {
        id: 4,
        userId: '',
        title: 'Fashion Trends CG',
        date: '2020/05/12',
        time: '18:00',
        address: { street: 'rua festeja', neighborhood: 'centro', city: 'campo grande' },
        ticket: '0',
        link: '',
        description: 'pula fogueira ',
        categoryId: 15,
        imgUrl: '../assets/statics/avatar01.jpg',
      },
      {
        id: 5,
        userId: '',
        title: 'Mis Hitchcok',
        date: '2020/05/16',
        time: '18:00',
        address: { street: 'rua festeja', neighborhood: 'centro', city: 'campo grande' },
        ticket: '0',
        link: '',
        description: 'pula fogueira Lorem Ipsum é simplesmente uma simulação de texto',
        categoryId: 10,
        imgUrl: '../assets/statics/avatar01.jpg',
      },
      {
        id: 6,
        userId: '',
        title: 'Festa Junina',
        date: '2020/05/21',
        time: '18:00',
        address: { street: 'rua festeja', neighborhood: 'centro', city: 'campo grande' },
        ticket: '0',
        link: '',
        description: 'pula fogueira ',
        categoryId: 5,
        imgUrl: '../assets/statics/avatar01.jpg',
      },
      {
        id: 7,
        userId: '',
        title: 'Photo Export',
        date: '2020/05/23',
        time: '18:00',
        address: { street: 'rua festeja', neighborhood: 'centro', city: 'campo grande' },
        ticket: '0',
        link: '',
        description: 'pula fogueira Lorem Ipsum é simplesmente uma simulação de texto',
        categoryId: 8,
        imgUrl: '../assets/statics/avatar01.jpg',
      },
      {
        id: 8,
        userId: '',
        title: 'Print',
        date: '2020/05/28',
        time: '18:00',
        address: { street: 'rua festeja', neighborhood: 'centro', city: 'campo grande' },
        ticket: '0',
        link: '',
        description: 'pula fogueira ',
        categoryId: 4,
        imgUrl: '../assets/statics/avatar01.jpg',
      },
      {
        id: 9,
        userId: '',
        title: 'Dance_Fest',
        date: '2020/05/30',
        time: '18:00',
        address: { street: 'Rua do Dinar', neighborhood: 'Vila Carlota', city: 'campo grande' },
        ticket: '0',
        link: 'https://www.facebook.com/henriquemleonel',
        description: 'Festival de dança da comunidade para a comunidade, venha se divertir',
        categoryId: 1,
        imgUrl: '../assets/statics/avatar01.jpg',
      },
      {
        id: 10,
        userId: '',
        title: 'Festival Forró',
        date: '2020/06/01',
        time: '18:00',
        address: { street: 'rua festeja', neighborhood: 'centro', city: 'campo grande' },
        ticket: '0',
        link: 'https://www.facebook.com/henriquemleonel',
        description: 'pula fogueira',
        categoryId: 12,
        imgUrl: '../assets/statics/avatar01.jpg',
      },
      {
        id: 11,
        userId: '',
        title: 'Coo ka',
        date: '2020/08/03',
        time: '18:00',
        address: { street: 'rua festeja', neighborhood: 'centro', city: 'campo grande' },
        ticket: '0',
        link: 'https://www.facebook.com/henriquemleonel',
        description: 'fol clore sse',
        categoryId: 13,
        imgUrl: '../assets/statics/avatar01.jpg',
      },
    ],
  },

  getters: {
    loadEvents: (state) => state.events,
  },
};
