import Vue from 'vue'

import './styles/quasar.scss'
import '@quasar/extras/roboto-font/roboto-font.css'
import '@quasar/extras/fontawesome-v5/fontawesome-v5.css'
import '@quasar/extras/material-icons/material-icons.css'
import {
  ClosePopup,
  QAvatar,
  QBadge,
  QBtn,
  QBtnToggle,
  QCard,
  QCardActions,
  QCardSection,
  QCarousel,
  QCarouselControl,
  QCarouselSlide,
  QCheckbox,
  QChip,
  QDate,
  QDialog,
  QDrawer,
  QEditor,
  QExpansionItem,
  QHeader,
  QIcon,
  QImg,
  QInput,
  QItem,
  QItemLabel,
  QItemSection,
  QLayout,
  QList,
  QOptionGroup,
  QPage,
  QPageContainer,
  QParallax,
  QRadio,
  QRouteTab,
  QScrollArea,
  QSelect,
  QSeparator,
  QSlideItem,
  QSlideTransition,
  QSpace,
  QSplitter,
  QStep,
  QStepper,
  QStepperNavigation,
  QTab,
  QTable,
  QTabs,
  QTimeline,
  QTimelineEntry,
  QToggle,
  QToolbar,
  QToolbarTitle,
  QTooltip,
  Quasar,
  QUploader,
} from 'quasar'

Vue.use(Quasar, {
  config: {
    extras: [
      'fontawesome-v5',
    ],
    brand: {
      // definir aqui suas cores padroes
      primary: '#050302',
      secondary: '#00ff00',
      // accent: '',
      // dark: '',
      // positive: '',
      // negative: '',
      // info: '',
      // warning: '',
    }
  },
  components: {
    ClosePopup,
    QAvatar,
    QBadge,
    QBtn,
    QBtnToggle,
    QCard,
    QCardActions,
    QCardSection,
    QCarousel,
    QCarouselControl,
    QCarouselSlide,
    QCheckbox,
    QChip,
    QDate,
    QDialog,
    QDrawer,
    QEditor,
    QExpansionItem,
    QHeader,
    QIcon,
    QImg,
    QInput,
    QItem,
    QItemLabel,
    QItemSection,
    QLayout,
  QList,
    QOptionGroup,
    QPage,
    QPageContainer,
    QParallax,
    QRadio,
    QRouteTab,
    QScrollArea,
    QSelect,
    QSeparator,
    QSlideItem,
    QSlideTransition,
    QSpace,
    QSplitter,
    QStep,
    QStepper,
    QStepperNavigation,
    QTab,
    QTable,
    QTabs,
    QTimeline,
    QTimelineEntry,
    QToggle,
    QToolbar,
    QToolbarTitle,
    QTooltip,
    Quasar,
    QUploader,
  },
  directives: {
    ClosePopup
  },
  plugins: {}
})
